<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jh_photoswipe"
 *
 * Auto generated by Extension Builder 2015-03-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'PhotoSwipe',
    'description' => 'Adds the wonderful Photoswipe (http://photoswipe.com/) JavaScript gallery as a plugin to TYPO3 CMS.',
    'category' => 'plugin',
    'author' => 'Jonathan Heilmann',
    'author_email' => 'mail@jonathan-heilmann.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.2',
    'constraints' => array(
        'depends' => array(
            'typo3' => '6.2.0-7.6.99',
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
